import Head from "next/head";

export default function CreatePage(){
  return(
    <>
      <Head>
        <title>Create Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h4>Create Quiz</h4>
      </main>
    </>
  )
}